name: fluttercon
description: "A new Flutter project."
publish_to: 'none'
version: 1.18.01+11801

environment:
  sdk: ">=3.5.0 <4.0.0"

isar_version: &isar_version 3.1.8

dependencies:
  appinio_social_share: ^0.3.2
  auth_buttons: ^3.0.3
  auto_size_text: ^3.0.0
  # awesome_notifications: ^0.10.1
  bloc: ^9.0.0
  build_version: ^2.1.1
  cached_network_image: ^3.4.1
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  firebase_analytics: ^11.3.3
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_crashlytics: ^4.2.0
  firebase_remote_config: ^5.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_local_notifications: ^19.0.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.16
  freezed_annotation: ^3.0.0
  get_it: ^8.0.2
  go_router: ^14.6.2
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^2.5.0
  intl: ^0.19.0
  isar:
    version: *isar_version
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs: # contains Isar Core
    version: *isar_version
    hosted: https://pub.isar-community.dev/
  jiffy: ^6.3.2
  json_annotation: ^4.9.0
  logger: ^2.4.0
  path_provider: ^2.1.5
  pretty_dio_logger: ^1.4.0
  share_plus: ^10.1.1
  sizer: ^3.0.4
  # timeago: ^3.7.0
  timeline_tile: ^2.0.0
  timezone: ^0.10.0
  url_launcher: ^6.3.1
  wolt_modal_sheet: ^0.11.0

dev_dependencies:
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.2
  flutter_test:
    sdk: flutter
  freezed: ^3.0.0-0.0.dev
  hive_generator: ^2.0.1
  icons_launcher: ^3.0.0
  injectable_generator: ^2.4.2
  isar_generator:
    version: *isar_version
    hosted: https://pub.isar-community.dev/
  json_serializable: ^6.8.0
  mocktail: ^1.0.3
  very_good_analysis: ^7.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/social-media/
    - assets/images/
    - assets/google_fonts/
